#!/bin/bash

NAME="neovim"
URL="https://github.com/neovim/neovim"
DIR=$( dirname $0 )

sudo pip3 install neovim
[ "${DIR}" == "." ] && SPEC="${NAME}.spec" || SPEC="${DIR}/${NAME}.spec"
git-build-rpm -n "${NAME}" -u "${URL}" -s "${SPEC}" -b release-0.3
