#!/bin/bash

NAME="log4cpp"
URL="https://github.com/msaf1980/${NAME}"
DIR=$( dirname $0 )
[ "${DIR}" == "." ] && SPEC="${NAME}.spec" || SPEC="${DIR}/${NAME}.spec"
git-build-rpm -u "${URL}" -s "${SPEC}"
